# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cb1OperationSoft.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *


class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        # MainWindow.resize(897, 743)
        MainWindow.setFixedSize(897, 743)  # 禁止窗口缩放
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setAnimated(False)
        # MainWindow.setStyleSheet("background-color: rgb(10, 69, 107);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 871, 721))
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        # self.tabWidget.setStyleSheet("background-color: rgb(255, 255, 255);")

        # <editor-fold desc="tabwidget - Tool 1">
        self.tab = QtWidgets.QWidget()
        self.tab.setToolTip("")
        self.tab.setObjectName("tab")

        # <editor-fold desc="MainWindow Tool's Title">
        self.titleLabel = QtWidgets.QLabel(self.tab)
        self.titleLabel.setToolTip('该工具用于目标楼层的底图添加：\n'
                                   'a).目标高层的所有楼层在GIS中统一出图，图像大小保持一致\n'
                                   'b).在Momoda软件中复制已做的楼层，添加每层的uid，如楼层b1和f1\n'
                                   'c).利用该工具自动添加目标楼层的底图\n'
                                   'd).楼层编码(uid)前缀:地下(b),地上(f),夹层(m),楼顶(t),\n'
                                   '例如：3-4层的夹层命名为m3；楼顶t67\n'
                                   )
        self.titleLabel.setGeometry(QtCore.QRect(290, 50, 281, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.titleLabel.setFont(font)
        self.titleLabel.setTextFormat(QtCore.Qt.AutoText)
        self.titleLabel.setScaledContents(False)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setWordWrap(False)
        self.titleLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.titleLabel.setObjectName("titleLabel")

        # </editor-fold>

        # <editor-fold desc="cb1 Add module,include: label button text">
        self.cb1Label = QtWidgets.QLabel(self.tab)
        self.cb1Label.setGeometry(QtCore.QRect(60, 90, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.cb1Label.setFont(font)
        self.cb1Label.setTextFormat(QtCore.Qt.AutoText)
        self.cb1Label.setScaledContents(False)
        self.cb1Label.setAlignment(QtCore.Qt.AlignLeft)
        self.cb1Label.setWordWrap(False)
        self.cb1Label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.cb1Label.setObjectName("Cb1 Label")

        self.cb1Button = QtWidgets.QPushButton(self.tab)
        self.cb1Button.setGeometry(QtCore.QRect(780, 120, 51, 31))
        self.cb1Button.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.cb1Button.setObjectName("cb1 File Add Button")

        self.cb1lineEdit = QtWidgets.QLineEdit(self.tab)
        self.cb1lineEdit.setGeometry(QtCore.QRect(60, 120, 691, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cb1lineEdit.setFont(font)
        self.cb1lineEdit.setObjectName("Cb1 File lineEdit")
        # </editor-fold>

        # <editor-fold desc="Base Map Add module,include: label button text">
        self.bmLabel = QtWidgets.QLabel(self.tab)
        self.bmLabel.setGeometry(QtCore.QRect(60, 170, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.bmLabel.setFont(font)
        self.bmLabel.setTextFormat(QtCore.Qt.AutoText)
        self.bmLabel.setScaledContents(False)
        self.bmLabel.setAlignment(QtCore.Qt.AlignLeft)
        self.bmLabel.setWordWrap(False)
        self.bmLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.bmLabel.setObjectName("bmLabel")

        self.bmButton = QtWidgets.QPushButton(self.tab)
        self.bmButton.setGeometry(QtCore.QRect(780, 200, 51, 31))
        self.bmButton.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.bmButton.setObjectName("Base Map Add Button")

        self.bmlineEdit = QtWidgets.QLineEdit(self.tab)
        self.bmlineEdit.setGeometry(QtCore.QRect(60, 200, 691, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.bmlineEdit.setFont(font)
        self.bmlineEdit.setObjectName("Base Map lineEdit")
        # </editor-fold>

        # <editor-fold desc="Floor Module: fill with 'floor' string">
        self.floorLabel = QtWidgets.QLabel(self.tab)
        self.floorLabel.setToolTip('输入目标楼层\n'
                                   '如：地上一层 f1，地下一层 b1')
        self.floorLabel.setGeometry(QtCore.QRect(60, 250, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.floorLabel.setFont(font)
        self.floorLabel.setTextFormat(QtCore.Qt.AutoText)
        self.floorLabel.setScaledContents(False)
        self.floorLabel.setAlignment(QtCore.Qt.AlignLeft)
        self.floorLabel.setWordWrap(False)
        self.floorLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.floorLabel.setObjectName("floorLabel")

        self.floorlineEdit = QtWidgets.QLineEdit(self.tab)
        self.floorlineEdit.setGeometry(QtCore.QRect(60, 280, 331, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.floorlineEdit.setFont(font)
        self.floorlineEdit.setObjectName("floorlineEdit")

        self.checkBox = QtWidgets.QCheckBox(self.tab)
        self.checkBox.setGeometry(QtCore.QRect(460, 280, 291, 31))
        # self.checkBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        # self.checkBox.toggle()
        self.checkBox.setObjectName("checkBox")
        # </editor-fold>

        # <editor-fold desc="Campus Builder User basemap folder path add">
        self.umLabel = QtWidgets.QLabel(self.tab)
        self.umLabel.setToolTip('添加Momoda程序的BaseMaps的路径\n'
                                '例如：'
                                r'D:\Program Files (x86)\CampusBuilderx64_cn\UserData\BaseMaps'
                                )
        self.umLabel.setGeometry(QtCore.QRect(60, 330, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.umLabel.setFont(font)
        self.umLabel.setTextFormat(QtCore.Qt.AutoText)
        self.umLabel.setScaledContents(False)
        self.umLabel.setAlignment(QtCore.Qt.AlignLeft)
        self.umLabel.setWordWrap(False)
        self.umLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.umLabel.setObjectName("umLabel")

        self.umFolder = QtWidgets.QPushButton(self.tab)
        self.umFolder.setGeometry(QtCore.QRect(780, 360, 51, 31))
        self.umFolder.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.umFolder.setObjectName("folder path Open")

        self.umlineEdit = QtWidgets.QLineEdit(self.tab)
        self.umlineEdit.setGeometry(QtCore.QRect(60, 360, 691, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.umlineEdit.setFont(font)
        self.umlineEdit.setObjectName("User Map lineEdit")
        # </editor-fold>

        # <editor-fold desc="Log and Run Module">
        self.logLabel = QtWidgets.QLabel(self.tab)
        self.logLabel.setGeometry(QtCore.QRect(60, 490, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.logLabel.setFont(font)
        self.logLabel.setTextFormat(QtCore.Qt.AutoText)
        self.logLabel.setScaledContents(False)
        self.logLabel.setAlignment(QtCore.Qt.AlignLeft)
        self.logLabel.setWordWrap(False)
        self.logLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.logLabel.setObjectName("logLabel")

        self.exeRun = QtWidgets.QPushButton(self.tab)
        self.exeRun.setGeometry(QtCore.QRect(340, 460, 141, 31))
        self.exeRun.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.exeRun.setObjectName("exeRun")

        self.logtextEdit = QtWidgets.QTextEdit(self.tab)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.logtextEdit.setFont(font)
        self.logtextEdit.setGeometry(QtCore.QRect(60, 520, 691, 141))
        self.logtextEdit.setReadOnly(True)
        self.logtextEdit.setStyleSheet("background-color: rgb(67, 67, 67);\n"
                                       "color: rgb(255, 255, 255);")
        self.logtextEdit.setObjectName("logtextEdit")
        # </editor-fold>
        self.tabWidget.addTab(self.tab, "")
        # </editor-fold>

        # <editor-fold desc="tabwidget - Tool 2">
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")

        # <editor-fold desc="MainWindow Tool's Title">
        self.titleLabel_2 = QtWidgets.QLabel(self.tab_2)
        self.titleLabel_2.setToolTip('该工具用于 cb1 文件属性信息的统计和添加：\n'
                                     'a).统计插入的模型种类，生成UserLib.xls\n'
                                     'b).在UserLib.xls，手动添加所需字段value信息\n'
                                     'c).最后，为 cb1 文件，批量添加属性'
                                     )
        self.titleLabel_2.setGeometry(QtCore.QRect(200, 40, 450, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.titleLabel_2.setFont(font)
        self.titleLabel_2.setTextFormat(QtCore.Qt.AutoText)
        self.titleLabel_2.setScaledContents(False)
        self.titleLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel_2.setWordWrap(False)
        self.titleLabel_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.titleLabel_2.setObjectName("titleLabel")

        # </editor-fold>

        # <editor-fold desc="cb1 Add module,include: label button text">
        self.cb1Label_2 = QtWidgets.QLabel(self.tab_2)
        self.cb1Label_2.setGeometry(QtCore.QRect(60, 70, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.cb1Label_2.setFont(font)
        self.cb1Label_2.setTextFormat(QtCore.Qt.AutoText)
        self.cb1Label_2.setScaledContents(False)
        self.cb1Label_2.setAlignment(QtCore.Qt.AlignLeft)
        self.cb1Label_2.setWordWrap(False)
        self.cb1Label_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.cb1Label_2.setObjectName("Cb1 Label")

        self.cb1Button_2 = QtWidgets.QPushButton(self.tab_2)
        self.cb1Button_2.setGeometry(QtCore.QRect(780, 100, 51, 31))
        self.cb1Button_2.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.cb1Button_2.setObjectName("cb1 File Add Button")

        self.cb1lineEdit_2 = QtWidgets.QLineEdit(self.tab_2)
        self.cb1lineEdit_2.setGeometry(QtCore.QRect(60, 100, 691, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cb1lineEdit.setFont(font)
        self.cb1lineEdit.setObjectName("Cb1 File lineEdit")
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cb1lineEdit_2.setFont(font)
        self.cb1lineEdit_2.setObjectName("Cb1 File lineEdit")
        # </editor-fold>

        # <editor-fold desc="Bundle Lib,include: label button text">
        self.bLibLabel = QtWidgets.QLabel(self.tab_2)
        self.bLibLabel.setGeometry(QtCore.QRect(60, 150, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.bLibLabel.setFont(font)
        self.bLibLabel.setTextFormat(QtCore.Qt.AutoText)
        self.bLibLabel.setScaledContents(False)
        self.bLibLabel.setAlignment(QtCore.Qt.AlignLeft)
        self.bLibLabel.setWordWrap(False)
        self.bLibLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.bLibLabel.setObjectName("bLibLabel")

        self.bLibButton = QtWidgets.QPushButton(self.tab_2)
        self.bLibButton.setGeometry(QtCore.QRect(780, 180, 51, 31))
        self.bLibButton.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.bLibButton.setObjectName("bLibButton")

        self.bLiblineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.bLiblineEdit.setGeometry(QtCore.QRect(60, 180, 691, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.bLiblineEdit.setFont(font)
        self.bLiblineEdit.setObjectName("bLiblineEdit")
        # </editor-fold>

        # <editor-fold desc="User Lib">
        self.uLibLabel = QtWidgets.QLabel(self.tab_2)
        self.uLibLabel.setGeometry(QtCore.QRect(60, 230, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.uLibLabel.setFont(font)
        self.uLibLabel.setTextFormat(QtCore.Qt.AutoText)
        self.uLibLabel.setScaledContents(False)
        self.uLibLabel.setAlignment(QtCore.Qt.AlignLeft)
        self.uLibLabel.setWordWrap(False)
        self.uLibLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.uLibLabel.setObjectName("uLibLabel")

        self.uLibButton = QtWidgets.QPushButton(self.tab_2)
        self.uLibButton.setGeometry(QtCore.QRect(780, 260, 51, 31))
        self.uLibButton.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.uLibButton.setObjectName("uLibButton")

        self.uLiblineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.uLiblineEdit.setGeometry(QtCore.QRect(60, 260, 691, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.uLiblineEdit.setFont(font)
        self.uLiblineEdit.setObjectName("uLiblineEdit")
        # </editor-fold>

        self.aStatisticButton = QtWidgets.QPushButton(self.tab_2)
        self.aStatisticButton.setGeometry(QtCore.QRect(540, 330, 161, 31))
        self.aStatisticButton.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.aStatisticButton.setObjectName("aStatisticButton")

        # <editor-fold desc="field add">
        self.fieldLabel = QtWidgets.QLabel(self.tab_2)
        self.fieldLabel.setGeometry(QtCore.QRect(60, 360, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.fieldLabel.setFont(font)
        self.fieldLabel.setTextFormat(QtCore.Qt.AutoText)
        self.fieldLabel.setScaledContents(False)
        self.fieldLabel.setAlignment(QtCore.Qt.AlignLeft)
        self.fieldLabel.setWordWrap(False)
        self.fieldLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.fieldLabel.setObjectName("fieldLabel")

        self.fieldlineEdit = QtWidgets.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fieldlineEdit.setFont(font)
        self.fieldlineEdit.setGeometry(QtCore.QRect(60, 390, 231, 31))
        self.fieldlineEdit.setObjectName("fieldlineEdit")
        # </editor-fold>

        # <editor-fold desc="Model Results Folder">
        self.mrFolderLabel = QtWidgets.QLabel(self.tab_2)
        self.mrFolderLabel.setGeometry(QtCore.QRect(330, 360, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.mrFolderLabel.setFont(font)
        self.mrFolderLabel.setTextFormat(QtCore.Qt.AutoText)
        self.mrFolderLabel.setScaledContents(False)
        self.mrFolderLabel.setAlignment(QtCore.Qt.AlignLeft)
        self.mrFolderLabel.setWordWrap(False)
        self.mrFolderLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.mrFolderLabel.setObjectName("mrFolderLabel")

        self.mrFolderButton = QtWidgets.QPushButton(self.tab_2)
        self.mrFolderButton.setGeometry(QtCore.QRect(780, 390, 51, 31))
        self.mrFolderButton.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.mrFolderButton.setObjectName("mrFolderButton")

        self.mrFolderlineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.mrFolderlineEdit.setGeometry(QtCore.QRect(330, 390, 421, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mrFolderlineEdit.setFont(font)
        self.mrFolderlineEdit.setObjectName("mrFolderlineEdit")
        # </editor-fold>

        self.outdoorCheckBox02 = QtWidgets.QCheckBox(self.tab_2)
        self.outdoorCheckBox02.setGeometry(QtCore.QRect(330, 450, 181, 31))
        self.outdoorCheckBox02.setToolTip('默认场景：Indoor scene')
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        self.outdoorCheckBox02.setFont(font)
        self.outdoorCheckBox02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.outdoorCheckBox02.setObjectName("outdoorCheckBox02")

        self.attrAddButton = QtWidgets.QPushButton(self.tab_2)
        self.attrAddButton.setGeometry(QtCore.QRect(540, 450, 161, 31))
        self.attrAddButton.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.attrAddButton.setObjectName("attrAddButton")

        # <editor-fold desc="Log">
        self.logLabel_2 = QtWidgets.QLabel(self.tab_2)
        self.logLabel_2.setGeometry(QtCore.QRect(60, 470, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.logLabel_2.setFont(font)
        self.logLabel_2.setTextFormat(QtCore.Qt.AutoText)
        self.logLabel_2.setScaledContents(False)
        self.logLabel_2.setAlignment(QtCore.Qt.AlignLeft)
        self.logLabel_2.setWordWrap(False)
        self.logLabel_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.logLabel_2.setObjectName("logLabel_2")

        self.logtextEdit_2 = QtWidgets.QTextEdit(self.tab_2)
        self.logtextEdit_2.setGeometry(QtCore.QRect(60, 500, 691, 141))
        self.logtextEdit_2.setReadOnly(True)
        self.logtextEdit_2.setStyleSheet("background-color: rgb(67, 67, 67);\n"
                                         "color: rgb(255, 255, 255);")
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.logtextEdit_2.setFont(font)
        self.logtextEdit_2.setObjectName("logtextEdit_2")
        # </editor-fold>

        self.tabWidget.addTab(self.tab_2, "")
        # </editor-fold>

        # <editor-fold desc="tabWidget - Tool 3">
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")

        # <editor-fold desc="Main Title">
        self.titleLabel_3 = QtWidgets.QLabel(self.tab_3)
        self.titleLabel_3.setGeometry(QtCore.QRect(270, 40, 281, 21))
        self.titleLabel_3.setToolTip('该工具用于 cb1 楼层的拼接：\n'
                                     '注）：需要将楼层多的场景放在第一个作为目标楼层，否则会出错，具体原因不知（后续测试）\n'
                                     '估计是楼层高度问题，超出的楼层在momoda软件里面不好定位，所以报错\n'
                                     )
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.titleLabel_3.setFont(font)
        self.titleLabel_3.setTextFormat(QtCore.Qt.AutoText)
        self.titleLabel_3.setScaledContents(False)
        self.titleLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel_3.setWordWrap(False)
        self.titleLabel_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.titleLabel_3.setObjectName("titleLabel_3")
        # </editor-fold>

        # <editor-fold desc="Cb1 Files">
        self.cb1Label_3 = QtWidgets.QLabel(self.tab_3)
        self.cb1Label_3.setGeometry(QtCore.QRect(40, 80, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.cb1Label_3.setFont(font)
        self.cb1Label_3.setTextFormat(QtCore.Qt.AutoText)
        self.cb1Label_3.setScaledContents(False)
        self.cb1Label_3.setAlignment(QtCore.Qt.AlignLeft)
        self.cb1Label_3.setWordWrap(False)
        self.cb1Label_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.cb1Label_3.setObjectName("cb1Label_3")

        self.cb1File_3 = QtWidgets.QPushButton(self.tab_3)
        self.cb1File_3.setGeometry(QtCore.QRect(760, 110, 51, 31))
        self.cb1File_3.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.cb1File_3.setObjectName("cb1File_3")

        self.cb1FilelineEdit_3 = QtWidgets.QLineEdit(self.tab_3)
        self.cb1FilelineEdit_3.setGeometry(QtCore.QRect(40, 110, 691, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cb1FilelineEdit_3.setFont(font)
        self.cb1FilelineEdit_3.setObjectName("cb1FilelineEdit_3")
        # </editor-fold>

        # <editor-fold desc="Cb1 Results Save">
        self.cb1SaveLabel = QtWidgets.QLabel(self.tab_3)
        self.cb1SaveLabel.setGeometry(QtCore.QRect(40, 180, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.cb1SaveLabel.setFont(font)
        self.cb1SaveLabel.setTextFormat(QtCore.Qt.AutoText)
        self.cb1SaveLabel.setScaledContents(False)
        self.cb1SaveLabel.setAlignment(QtCore.Qt.AlignLeft)
        self.cb1SaveLabel.setWordWrap(False)
        self.cb1SaveLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.cb1SaveLabel.setObjectName("cb1SaveLabel")

        self.cb1SaveButton = QtWidgets.QPushButton(self.tab_3)
        self.cb1SaveButton.setGeometry(QtCore.QRect(760, 210, 51, 31))
        self.cb1SaveButton.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.cb1SaveButton.setObjectName("cb1SaveButton")

        self.cb1SavelineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.cb1SavelineEdit.setGeometry(QtCore.QRect(40, 210, 691, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cb1SavelineEdit.setFont(font)
        self.cb1SavelineEdit.setObjectName("cb1SavelineEdit")
        # </editor-fold>

        # <editor-fold desc="Building Name Coding">
        self.bNameCodeLabel = QtWidgets.QLabel(self.tab_3)
        self.bNameCodeLabel.setGeometry(QtCore.QRect(40, 280, 180, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.bNameCodeLabel.setFont(font)
        self.bNameCodeLabel.setTextFormat(QtCore.Qt.AutoText)
        self.bNameCodeLabel.setScaledContents(False)
        self.bNameCodeLabel.setAlignment(QtCore.Qt.AlignLeft)
        self.bNameCodeLabel.setWordWrap(False)
        self.bNameCodeLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.bNameCodeLabel.setObjectName("bNameCodeLabel")

        self.bNameCodelineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.bNameCodelineEdit.setGeometry(QtCore.QRect(40, 310, 691, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.bNameCodelineEdit.setFont(font)
        self.bNameCodelineEdit.setObjectName("bNameCodelineEdit")
        # </editor-fold>

        self.floorMergeButton = QtWidgets.QPushButton(self.tab_3)
        self.floorMergeButton.setGeometry(QtCore.QRect(310, 400, 161, 31))
        self.floorMergeButton.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.floorMergeButton.setObjectName("floorMergeButton")

        # <editor-fold desc="Log">
        self.logLabel_3 = QtWidgets.QLabel(self.tab_3)
        self.logLabel_3.setGeometry(QtCore.QRect(40, 460, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.logLabel_3.setFont(font)
        self.logLabel_3.setTextFormat(QtCore.Qt.AutoText)
        self.logLabel_3.setScaledContents(False)
        self.logLabel_3.setAlignment(QtCore.Qt.AlignLeft)
        self.logLabel_3.setWordWrap(False)
        self.logLabel_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.logLabel_3.setObjectName("logLabel_3")

        self.logtextEdit_3 = QtWidgets.QTextEdit(self.tab_3)
        self.logtextEdit_3.setGeometry(QtCore.QRect(40, 490, 691, 141))
        self.logtextEdit_3.setReadOnly(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.logtextEdit_3.setFont(font)
        self.logtextEdit_3.setStyleSheet("background-color: rgb(67, 67, 67);\n"
                                         "color: rgb(255, 255, 255);")
        self.logtextEdit_3.setObjectName("logtextEdit_3")
        # </editor-fold>

        self.tabWidget.addTab(self.tab_3, "")
        # </editor-fold>

        # <editor-fold desc="tabWidget - Tool 4">
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.rFolderLabel_4 = QtWidgets.QLabel(self.tab_4)
        self.rFolderLabel_4.setGeometry(QtCore.QRect(40, 260, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.rFolderLabel_4.setFont(font)
        self.rFolderLabel_4.setTextFormat(QtCore.Qt.AutoText)
        self.rFolderLabel_4.setScaledContents(False)
        self.rFolderLabel_4.setWordWrap(False)
        self.rFolderLabel_4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.rFolderLabel_4.setObjectName("rFolderLabel_4")
        self.cb1Label_4 = QtWidgets.QLabel(self.tab_4)
        self.cb1Label_4.setGeometry(QtCore.QRect(40, 80, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.cb1Label_4.setFont(font)
        self.cb1Label_4.setTextFormat(QtCore.Qt.AutoText)
        self.cb1Label_4.setScaledContents(False)
        self.cb1Label_4.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.cb1Label_4.setWordWrap(False)
        self.cb1Label_4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.cb1Label_4.setObjectName("cb1Label_4")
        self.cb1File_4 = QtWidgets.QPushButton(self.tab_4)
        self.cb1File_4.setGeometry(QtCore.QRect(770, 110, 51, 31))
        self.cb1File_4.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.cb1File_4.setObjectName("cb1File_4")
        self.titleLabel_4 = QtWidgets.QLabel(self.tab_4)
        self.titleLabel_4.setGeometry(QtCore.QRect(250, 40, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.titleLabel_4.setFont(font)
        self.titleLabel_4.setTextFormat(QtCore.Qt.AutoText)
        self.titleLabel_4.setScaledContents(False)
        self.titleLabel_4.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel_4.setWordWrap(False)
        self.titleLabel_4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.titleLabel_4.setObjectName("titleLabel_4")
        self.cb1FilelineEdit_4 = QtWidgets.QLineEdit(self.tab_4)
        self.cb1FilelineEdit_4.setGeometry(QtCore.QRect(40, 110, 691, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cb1FilelineEdit_4.setFont(font)
        self.cb1FilelineEdit_4.setObjectName("cb1FilelineEdit_4")
        self.logtextEdit_4 = QtWidgets.QTextEdit(self.tab_4)
        self.logtextEdit_4.setGeometry(QtCore.QRect(40, 490, 691, 141))
        self.logtextEdit_4.setReadOnly(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.logtextEdit_4.setFont(font)
        self.logtextEdit_4.setStyleSheet("background-color: rgb(67, 67, 67);\n"
                                         "color: rgb(255, 255, 255);")
        self.logtextEdit_4.setObjectName("logtextEdit_4")
        self.logLabel_4 = QtWidgets.QLabel(self.tab_4)
        self.logLabel_4.setGeometry(QtCore.QRect(40, 460, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.logLabel_4.setFont(font)
        self.logLabel_4.setTextFormat(QtCore.Qt.AutoText)
        self.logLabel_4.setScaledContents(False)
        self.logLabel_4.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.logLabel_4.setWordWrap(False)
        self.logLabel_4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.logLabel_4.setObjectName("logLabel_4")
        self.rFolderlineEdit_4 = QtWidgets.QLineEdit(self.tab_4)
        self.rFolderlineEdit_4.setGeometry(QtCore.QRect(40, 290, 691, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rFolderlineEdit_4.setFont(font)
        self.rFolderlineEdit_4.setObjectName("rFolderlineEdit_4")
        self.jsIdRecodingBtn_4 = QtWidgets.QPushButton(self.tab_4)
        self.jsIdRecodingBtn_4.setGeometry(QtCore.QRect(310, 380, 161, 31))
        self.jsIdRecodingBtn_4.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.jsIdRecodingBtn_4.setObjectName("jsIdRecodingBtn_4")
        self.rFolderBtn_4 = QtWidgets.QPushButton(self.tab_4)
        self.rFolderBtn_4.setGeometry(QtCore.QRect(770, 290, 51, 31))
        self.rFolderBtn_4.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.rFolderBtn_4.setObjectName("rFolderBtn_4")
        self.bNameCodeLabel_2 = QtWidgets.QLabel(self.tab_4)
        self.bNameCodeLabel_2.setGeometry(QtCore.QRect(40, 170, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.bNameCodeLabel_2.setFont(font)
        self.bNameCodeLabel_2.setTextFormat(QtCore.Qt.AutoText)
        self.bNameCodeLabel_2.setScaledContents(False)
        self.bNameCodeLabel_2.setWordWrap(False)
        self.bNameCodeLabel_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.bNameCodeLabel_2.setObjectName("bNameCodeLabel_2")
        self.bNameCodelineEdit_2 = QtWidgets.QLineEdit(self.tab_4)
        self.bNameCodelineEdit_2.setGeometry(QtCore.QRect(40, 200, 691, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.bNameCodelineEdit_2.setFont(font)
        self.bNameCodelineEdit_2.setObjectName("bNameCodelineEdit_2")
        self.tabWidget.addTab(self.tab_4, "")
        # </editor-fold>

        # <editor-fold desc="tabWidget - Tool 5">
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.cb1File_5 = QtWidgets.QPushButton(self.tab_5)
        self.cb1File_5.setGeometry(QtCore.QRect(770, 110, 51, 31))
        self.cb1File_5.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.cb1File_5.setObjectName("cb1File_5")
        self.titleLabel_5 = QtWidgets.QLabel(self.tab_5)
        self.titleLabel_5.setGeometry(QtCore.QRect(150, 20, 481, 51))
        self.titleLabel_5.setToolTip('因为项目要求，需要将官方模型库的指定模型替换成自定义模型：\n'
                                     '1）需要3dmax，制作自定义模型，要求需要和官方模型的默认大小，方向一致；\n'
                                     '2）用模模搭，搭建室内辅助场景，model_scene；\n'
                                     '3) 替换修改目标场景中的‘bIdLists’项，添加CustomModel 文件夹。\n'
                                     '注) 想要使用该工具，需要先使用Tool 2 ，先通过Attributes Statistic工具\n'
                                     '将自定义模型加入到UserLib中，进行模型的属性修改，修改后，再使用该工具进行指定模型的替换。')
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.titleLabel_5.setFont(font)
        self.titleLabel_5.setTextFormat(QtCore.Qt.AutoText)
        self.titleLabel_5.setScaledContents(False)
        self.titleLabel_5.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel_5.setWordWrap(False)
        self.titleLabel_5.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.titleLabel_5.setObjectName("titleLabel_5")
        self.logLabel_5 = QtWidgets.QLabel(self.tab_5)
        self.logLabel_5.setGeometry(QtCore.QRect(40, 460, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.logLabel_5.setFont(font)
        self.logLabel_5.setTextFormat(QtCore.Qt.AutoText)
        self.logLabel_5.setScaledContents(False)
        self.logLabel_5.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.logLabel_5.setWordWrap(False)
        self.logLabel_5.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.logLabel_5.setObjectName("logLabel_5")
        self.modelMmdLabel = QtWidgets.QLabel(self.tab_5)
        self.modelMmdLabel.setGeometry(QtCore.QRect(40, 80, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.modelMmdLabel.setFont(font)
        self.modelMmdLabel.setTextFormat(QtCore.Qt.AutoText)
        self.modelMmdLabel.setScaledContents(False)
        self.modelMmdLabel.setWordWrap(False)
        self.modelMmdLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.modelMmdLabel.setObjectName("modelMmdLabel")
        self.cb1FilelineEdit_5 = QtWidgets.QLineEdit(self.tab_5)
        self.cb1FilelineEdit_5.setGeometry(QtCore.QRect(360, 110, 371, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cb1FilelineEdit_5.setFont(font)
        self.cb1FilelineEdit_5.setObjectName("cb1FilelineEdit_5")
        self.cusCb1Label_5 = QtWidgets.QLabel(self.tab_5)
        self.cusCb1Label_5.setGeometry(QtCore.QRect(360, 160, 331, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.cusCb1Label_5.setFont(font)
        self.cusCb1Label_5.setTextFormat(QtCore.Qt.AutoText)
        self.cusCb1Label_5.setScaledContents(False)
        self.cusCb1Label_5.setWordWrap(False)
        self.cusCb1Label_5.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.cusCb1Label_5.setObjectName("cusCb1Label_5")
        self.cusCb1lineEdit_5 = QtWidgets.QLineEdit(self.tab_5)
        self.cusCb1lineEdit_5.setGeometry(QtCore.QRect(360, 190, 371, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cusCb1lineEdit_5.setFont(font)
        self.cusCb1lineEdit_5.setObjectName("cusCb1lineEdit_5")
        self.logtextEdit_5 = QtWidgets.QTextEdit(self.tab_5)
        self.logtextEdit_5.setGeometry(QtCore.QRect(40, 490, 691, 141))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.logtextEdit_5.setFont(font)
        self.logtextEdit_5.setStyleSheet("background-color: rgb(67, 67, 67);\n"
                                         "color: rgb(255, 255, 255);")
        self.logtextEdit_5.setReadOnly(True)
        self.logtextEdit_5.setObjectName("logtextEdit_5")

        self.outdoorCheckBox05 = QtWidgets.QCheckBox(self.tab_5)
        self.outdoorCheckBox05.setGeometry(QtCore.QRect(160, 420, 191, 31))
        self.outdoorCheckBox05.setToolTip('默认场景：Indoor scene')
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        self.outdoorCheckBox05.setFont(font)
        self.outdoorCheckBox05.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.outdoorCheckBox05.setObjectName("outdoorCheckBox05")

        self.cusModelRunBtn_5 = QtWidgets.QPushButton(self.tab_5)
        self.cusModelRunBtn_5.setGeometry(QtCore.QRect(420, 420, 161, 31))
        self.cusModelRunBtn_5.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.cusModelRunBtn_5.setObjectName("cusModelRunBtn_5")
        self.modelMmdlineEdit = QtWidgets.QLineEdit(self.tab_5)
        self.modelMmdlineEdit.setGeometry(QtCore.QRect(40, 110, 271, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.modelMmdlineEdit.setFont(font)
        self.modelMmdlineEdit.setObjectName("modelMmdlineEdit")
        self.cusCb1Btn_5 = QtWidgets.QPushButton(self.tab_5)
        self.cusCb1Btn_5.setGeometry(QtCore.QRect(770, 190, 51, 31))
        self.cusCb1Btn_5.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.cusCb1Btn_5.setObjectName("cusCb1Btn_5")
        self.cb1Label_5 = QtWidgets.QLabel(self.tab_5)
        self.cb1Label_5.setGeometry(QtCore.QRect(360, 80, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.cb1Label_5.setFont(font)
        self.cb1Label_5.setTextFormat(QtCore.Qt.AutoText)
        self.cb1Label_5.setScaledContents(False)
        self.cb1Label_5.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.cb1Label_5.setWordWrap(False)
        self.cb1Label_5.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.cb1Label_5.setObjectName("cb1Label_5")
        self.cusModelLabel = QtWidgets.QLabel(self.tab_5)
        self.cusModelLabel.setGeometry(QtCore.QRect(40, 160, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.cusModelLabel.setFont(font)
        self.cusModelLabel.setTextFormat(QtCore.Qt.AutoText)
        self.cusModelLabel.setScaledContents(False)
        self.cusModelLabel.setWordWrap(False)
        self.cusModelLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.cusModelLabel.setObjectName("cusModelLabel")
        self.cusModellineEdit = QtWidgets.QLineEdit(self.tab_5)
        self.cusModellineEdit.setGeometry(QtCore.QRect(40, 190, 271, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cusModellineEdit.setFont(font)
        self.cusModellineEdit.setObjectName("cusModellineEdit")
        self.rFolderlineEdit_5 = QtWidgets.QLineEdit(self.tab_5)
        self.rFolderlineEdit_5.setGeometry(QtCore.QRect(40, 350, 691, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rFolderlineEdit_5.setFont(font)
        self.rFolderlineEdit_5.setObjectName("rFolderlineEdit_5")
        self.rFolderLabel_5 = QtWidgets.QLabel(self.tab_5)
        self.rFolderLabel_5.setGeometry(QtCore.QRect(40, 320, 331, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.rFolderLabel_5.setFont(font)
        self.rFolderLabel_5.setTextFormat(QtCore.Qt.AutoText)
        self.rFolderLabel_5.setScaledContents(False)
        self.rFolderLabel_5.setWordWrap(False)
        self.rFolderLabel_5.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.rFolderLabel_5.setObjectName("rFolderLabel_5")
        self.rFolderBtn_5 = QtWidgets.QPushButton(self.tab_5)
        self.rFolderBtn_5.setGeometry(QtCore.QRect(770, 350, 51, 31))
        self.rFolderBtn_5.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.rFolderBtn_5.setObjectName("rFolderBtn_5")
        self.uLiblineEdit_5 = QtWidgets.QLineEdit(self.tab_5)
        self.uLiblineEdit_5.setGeometry(QtCore.QRect(40, 270, 691, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.uLiblineEdit_5.setFont(font)
        self.uLiblineEdit_5.setObjectName("uLiblineEdit_5")
        self.uLibLabel_5 = QtWidgets.QLabel(self.tab_5)
        self.uLibLabel_5.setGeometry(QtCore.QRect(40, 240, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.uLibLabel_5.setFont(font)
        self.uLibLabel_5.setTextFormat(QtCore.Qt.AutoText)
        self.uLibLabel_5.setScaledContents(False)
        self.uLibLabel_5.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.uLibLabel_5.setWordWrap(False)
        self.uLibLabel_5.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.uLibLabel_5.setObjectName("uLibLabel_5")
        self.uLibBtn_5 = QtWidgets.QPushButton(self.tab_5)
        self.uLibBtn_5.setGeometry(QtCore.QRect(770, 270, 51, 31))
        self.uLibBtn_5.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.uLibBtn_5.setObjectName("uLibBtn_5")
        self.tabWidget.addTab(self.tab_5, "")
        # </editor-fold>

        # <editor-fold desc="tabWidget - Tool 6">
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.cb1File_6 = QtWidgets.QPushButton(self.tab_6)
        self.cb1File_6.setGeometry(QtCore.QRect(770, 110, 51, 31))
        self.cb1File_6.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.cb1File_6.setObjectName("cb1File_6")
        self.titleLabel_6 = QtWidgets.QLabel(self.tab_6)
        self.titleLabel_6.setGeometry(QtCore.QRect(210, 20, 361, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.titleLabel_6.setFont(font)
        self.titleLabel_6.setTextFormat(QtCore.Qt.AutoText)
        self.titleLabel_6.setScaledContents(False)
        self.titleLabel_6.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel_6.setWordWrap(False)
        self.titleLabel_6.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.titleLabel_6.setObjectName("titleLabel_6")
        self.logLabel_6 = QtWidgets.QLabel(self.tab_6)
        self.logLabel_6.setGeometry(QtCore.QRect(40, 460, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.logLabel_6.setFont(font)
        self.logLabel_6.setTextFormat(QtCore.Qt.AutoText)
        self.logLabel_6.setScaledContents(False)
        self.logLabel_6.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.logLabel_6.setWordWrap(False)
        self.logLabel_6.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.logLabel_6.setObjectName("logLabel_6")
        self.cb1FilelineEdit_6 = QtWidgets.QLineEdit(self.tab_6)
        self.cb1FilelineEdit_6.setGeometry(QtCore.QRect(40, 110, 691, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cb1FilelineEdit_6.setFont(font)
        self.cb1FilelineEdit_6.setObjectName("cb1FilelineEdit_6")
        self.rFolderlineEdit_6 = QtWidgets.QLineEdit(self.tab_6)
        self.rFolderlineEdit_6.setGeometry(QtCore.QRect(40, 290, 691, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rFolderlineEdit_6.setFont(font)
        self.rFolderlineEdit_6.setObjectName("rFolderlineEdit_6")
        self.rFolderLabel_6 = QtWidgets.QLabel(self.tab_6)
        self.rFolderLabel_6.setGeometry(QtCore.QRect(40, 260, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.rFolderLabel_6.setFont(font)
        self.rFolderLabel_6.setTextFormat(QtCore.Qt.AutoText)
        self.rFolderLabel_6.setScaledContents(False)
        self.rFolderLabel_6.setWordWrap(False)
        self.rFolderLabel_6.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.rFolderLabel_6.setObjectName("rFolderLabel_6")
        self.logtextEdit_6 = QtWidgets.QTextEdit(self.tab_6)
        self.logtextEdit_6.setGeometry(QtCore.QRect(40, 490, 691, 141))
        self.logtextEdit_6.setReadOnly(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.logtextEdit_6.setFont(font)
        self.logtextEdit_6.setStyleSheet("background-color: rgb(67, 67, 67);\n"
                                         "color: rgb(255, 255, 255);")
        self.logtextEdit_6.setObjectName("logtextEdit_6")
        self.versionRunBtn_6 = QtWidgets.QPushButton(self.tab_6)
        self.versionRunBtn_6.setGeometry(QtCore.QRect(310, 380, 161, 31))
        self.versionRunBtn_6.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.versionRunBtn_6.setObjectName("versionRunBtn_6")
        self.rFolderBtn_6 = QtWidgets.QPushButton(self.tab_6)
        self.rFolderBtn_6.setGeometry(QtCore.QRect(770, 290, 51, 31))
        self.rFolderBtn_6.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.rFolderBtn_6.setObjectName("rFolderBtn_6")
        self.cb1Label_6 = QtWidgets.QLabel(self.tab_6)
        self.cb1Label_6.setGeometry(QtCore.QRect(40, 80, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.cb1Label_6.setFont(font)
        self.cb1Label_6.setTextFormat(QtCore.Qt.AutoText)
        self.cb1Label_6.setScaledContents(False)
        self.cb1Label_6.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.cb1Label_6.setWordWrap(False)
        self.cb1Label_6.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.cb1Label_6.setObjectName("cb1Label_6")
        self.bNamelineEdit_6 = QtWidgets.QLineEdit(self.tab_6)
        self.bNamelineEdit_6.setGeometry(QtCore.QRect(40, 200, 311, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.bNamelineEdit_6.setFont(font)
        self.bNamelineEdit_6.setObjectName("bNamelineEdit_6")
        self.bNameLabel_6 = QtWidgets.QLabel(self.tab_6)
        self.bNameLabel_6.setGeometry(QtCore.QRect(40, 170, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.bNameLabel_6.setFont(font)
        self.bNameLabel_6.setTextFormat(QtCore.Qt.AutoText)
        self.bNameLabel_6.setScaledContents(False)
        self.bNameLabel_6.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.bNameLabel_6.setWordWrap(False)
        self.bNameLabel_6.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.bNameLabel_6.setObjectName("bNameLabel_6")
        self.versionLabel_6 = QtWidgets.QLabel(self.tab_6)
        self.versionLabel_6.setGeometry(QtCore.QRect(420, 170, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.versionLabel_6.setFont(font)
        self.versionLabel_6.setTextFormat(QtCore.Qt.AutoText)
        self.versionLabel_6.setScaledContents(False)
        self.versionLabel_6.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.versionLabel_6.setWordWrap(False)
        self.versionLabel_6.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.versionLabel_6.setObjectName("versionLabel_6")
        self.versionlineEdit_6 = QtWidgets.QLineEdit(self.tab_6)
        self.versionlineEdit_6.setGeometry(QtCore.QRect(420, 200, 311, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.versionlineEdit_6.setFont(font)
        self.versionlineEdit_6.setObjectName("versionlineEdit_6")
        self.tabWidget.addTab(self.tab_6, "")
        # </editor-fold>

        # <editor-fold desc="tabWidget - Tool 7">
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.modelShapeBtn_7 = QtWidgets.QPushButton(self.tab_7)
        self.modelShapeBtn_7.setGeometry(QtCore.QRect(310, 410, 161, 31))
        self.modelShapeBtn_7.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.modelShapeBtn_7.setObjectName("modelShapeBtn_7")
        self.cb1Label_7 = QtWidgets.QLabel(self.tab_7)
        self.cb1Label_7.setGeometry(QtCore.QRect(430, 90, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.cb1Label_7.setFont(font)
        self.cb1Label_7.setTextFormat(QtCore.Qt.AutoText)
        self.cb1Label_7.setScaledContents(False)
        self.cb1Label_7.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.cb1Label_7.setWordWrap(False)
        self.cb1Label_7.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.cb1Label_7.setObjectName("cb1Label_7")
        self.cb1File_7 = QtWidgets.QPushButton(self.tab_7)
        self.cb1File_7.setGeometry(QtCore.QRect(770, 120, 51, 31))
        self.cb1File_7.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.cb1File_7.setObjectName("cb1File_7")
        self.rFolderlineEdit_7 = QtWidgets.QLineEdit(self.tab_7)
        self.rFolderlineEdit_7.setGeometry(QtCore.QRect(40, 330, 691, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rFolderlineEdit_7.setFont(font)
        self.rFolderlineEdit_7.setObjectName("rFolderlineEdit_7")
        self.rFolderBtn_7 = QtWidgets.QPushButton(self.tab_7)
        self.rFolderBtn_7.setGeometry(QtCore.QRect(770, 330, 51, 31))
        self.rFolderBtn_7.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.rFolderBtn_7.setObjectName("rFolderBtn_7")
        self.logtextEdit_7 = QtWidgets.QTextEdit(self.tab_7)
        self.logtextEdit_7.setGeometry(QtCore.QRect(40, 490, 691, 141))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.logtextEdit_7.setFont(font)
        self.logtextEdit_7.setStyleSheet("background-color: rgb(67, 67, 67);\n"
                                         "color: rgb(255, 255, 255);")
        self.logtextEdit_7.setReadOnly(True)
        self.logtextEdit_7.setObjectName("logtextEdit_7")
        self.modelLabel_7 = QtWidgets.QLabel(self.tab_7)
        self.modelLabel_7.setGeometry(QtCore.QRect(40, 90, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.modelLabel_7.setFont(font)
        self.modelLabel_7.setTextFormat(QtCore.Qt.AutoText)
        self.modelLabel_7.setScaledContents(False)
        self.modelLabel_7.setWordWrap(False)
        self.modelLabel_7.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.modelLabel_7.setObjectName("modelLabel_7")
        self.cb1FilelineEdit_7 = QtWidgets.QLineEdit(self.tab_7)
        self.cb1FilelineEdit_7.setGeometry(QtCore.QRect(430, 120, 301, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cb1FilelineEdit_7.setFont(font)
        self.cb1FilelineEdit_7.setObjectName("cb1FilelineEdit_7")
        self.rFolderLabel_7 = QtWidgets.QLabel(self.tab_7)
        self.rFolderLabel_7.setGeometry(QtCore.QRect(40, 300, 331, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.rFolderLabel_7.setFont(font)
        self.rFolderLabel_7.setTextFormat(QtCore.Qt.AutoText)
        self.rFolderLabel_7.setScaledContents(False)
        self.rFolderLabel_7.setWordWrap(False)
        self.rFolderLabel_7.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.rFolderLabel_7.setObjectName("rFolderLabel_7")
        self.modelLineEdit_7 = QtWidgets.QLineEdit(self.tab_7)
        self.modelLineEdit_7.setGeometry(QtCore.QRect(40, 120, 271, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.modelLineEdit_7.setFont(font)
        self.modelLineEdit_7.setObjectName("modelLineEdit_7")
        self.titleLabel_7 = QtWidgets.QLabel(self.tab_7)
        self.titleLabel_7.setGeometry(QtCore.QRect(60, 20, 661, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.titleLabel_7.setFont(font)
        self.titleLabel_7.setTextFormat(QtCore.Qt.AutoText)
        self.titleLabel_7.setScaledContents(False)
        self.titleLabel_7.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel_7.setWordWrap(False)
        self.titleLabel_7.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.titleLabel_7.setObjectName("titleLabel_7")
        self.logLabel_7 = QtWidgets.QLabel(self.tab_7)
        self.logLabel_7.setGeometry(QtCore.QRect(40, 460, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.logLabel_7.setFont(font)
        self.logLabel_7.setTextFormat(QtCore.Qt.AutoText)
        self.logLabel_7.setScaledContents(False)
        self.logLabel_7.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.logLabel_7.setWordWrap(False)
        self.logLabel_7.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.logLabel_7.setObjectName("logLabel_7")
        self.hPoseLabel_7 = QtWidgets.QLabel(self.tab_7)
        self.hPoseLabel_7.setGeometry(QtCore.QRect(40, 190, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.hPoseLabel_7.setFont(font)
        self.hPoseLabel_7.setTextFormat(QtCore.Qt.AutoText)
        self.hPoseLabel_7.setScaledContents(False)
        self.hPoseLabel_7.setWordWrap(False)
        self.hPoseLabel_7.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.hPoseLabel_7.setObjectName("hPoseLabel_7")
        self.hPoselineEdit_7 = QtWidgets.QLineEdit(self.tab_7)
        self.hPoselineEdit_7.setGeometry(QtCore.QRect(40, 220, 271, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.hPoselineEdit_7.setFont(font)
        self.hPoselineEdit_7.setObjectName("hPoselineEdit_7")
        self.hScalelineEdit_7 = QtWidgets.QLineEdit(self.tab_7)
        self.hScalelineEdit_7.setGeometry(QtCore.QRect(430, 220, 301, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.hScalelineEdit_7.setFont(font)
        self.hScalelineEdit_7.setObjectName("hScalelineEdit_7")
        self.hScaleLabel_7 = QtWidgets.QLabel(self.tab_7)
        self.hScaleLabel_7.setGeometry(QtCore.QRect(430, 190, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.hScaleLabel_7.setFont(font)
        self.hScaleLabel_7.setTextFormat(QtCore.Qt.AutoText)
        self.hScaleLabel_7.setScaledContents(False)
        self.hScaleLabel_7.setWordWrap(False)
        self.hScaleLabel_7.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.hScaleLabel_7.setObjectName("hScaleLabel_7")
        self.modelBtn_7 = QtWidgets.QPushButton(self.tab_7)
        self.modelBtn_7.setGeometry(QtCore.QRect(340, 120, 51, 31))
        self.modelBtn_7.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.modelBtn_7.setObjectName("modelBtn_7")
        self.tabWidget.addTab(self.tab_7, "")
        # </editor-fold>

        # <editor-fold desc="tabWidget - Tool 8">
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.AttrRunBtn_8 = QtWidgets.QPushButton(self.tab_8)
        self.AttrRunBtn_8.setGeometry(QtCore.QRect(560, 420, 171, 31))
        self.AttrRunBtn_8.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.AttrRunBtn_8.setObjectName("AttrRunBtn_8")
        self.cb1Label_8 = QtWidgets.QLabel(self.tab_8)
        self.cb1Label_8.setGeometry(QtCore.QRect(40, 80, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.cb1Label_8.setFont(font)
        self.cb1Label_8.setTextFormat(QtCore.Qt.AutoText)
        self.cb1Label_8.setScaledContents(False)
        self.cb1Label_8.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.cb1Label_8.setWordWrap(False)
        self.cb1Label_8.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.cb1Label_8.setObjectName("cb1Label_8")
        self.cb1File_8 = QtWidgets.QPushButton(self.tab_8)
        self.cb1File_8.setGeometry(QtCore.QRect(770, 110, 51, 31))
        self.cb1File_8.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.cb1File_8.setObjectName("cb1File_8")
        self.rFolderlineEdit_8 = QtWidgets.QLineEdit(self.tab_8)
        self.rFolderlineEdit_8.setGeometry(QtCore.QRect(450, 350, 281, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rFolderlineEdit_8.setFont(font)
        self.rFolderlineEdit_8.setObjectName("rFolderlineEdit_8")
        self.rFolderBtn_8 = QtWidgets.QPushButton(self.tab_8)
        self.rFolderBtn_8.setGeometry(QtCore.QRect(770, 350, 51, 31))
        self.rFolderBtn_8.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.rFolderBtn_8.setObjectName("rFolderBtn_8")
        self.logtextEdit_8 = QtWidgets.QTextEdit(self.tab_8)
        self.logtextEdit_8.setGeometry(QtCore.QRect(40, 490, 691, 141))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.logtextEdit_8.setFont(font)
        self.logtextEdit_8.setStyleSheet("background-color: rgb(67, 67, 67);\n"
                                         "color: rgb(255, 255, 255);")
        self.logtextEdit_8.setReadOnly(True)
        self.logtextEdit_8.setObjectName("logtextEdit_8")
        self.modelLabel_8 = QtWidgets.QLabel(self.tab_8)
        self.modelLabel_8.setGeometry(QtCore.QRect(40, 160, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.modelLabel_8.setFont(font)
        self.modelLabel_8.setTextFormat(QtCore.Qt.AutoText)
        self.modelLabel_8.setScaledContents(False)
        self.modelLabel_8.setWordWrap(False)
        self.modelLabel_8.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.modelLabel_8.setObjectName("modelLabel_8")
        self.cb1FilelineEdit_8 = QtWidgets.QLineEdit(self.tab_8)
        self.cb1FilelineEdit_8.setGeometry(QtCore.QRect(40, 110, 691, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cb1FilelineEdit_8.setFont(font)
        self.cb1FilelineEdit_8.setObjectName("cb1FilelineEdit_8")
        self.rFolderLabel_8 = QtWidgets.QLabel(self.tab_8)
        self.rFolderLabel_8.setGeometry(QtCore.QRect(450, 320, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.rFolderLabel_8.setFont(font)
        self.rFolderLabel_8.setTextFormat(QtCore.Qt.AutoText)
        self.rFolderLabel_8.setScaledContents(False)
        self.rFolderLabel_8.setWordWrap(False)
        self.rFolderLabel_8.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.rFolderLabel_8.setObjectName("rFolderLabel_8")
        self.modelLineEdit_8 = QtWidgets.QLineEdit(self.tab_8)
        self.modelLineEdit_8.setGeometry(QtCore.QRect(40, 190, 271, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.modelLineEdit_8.setFont(font)
        self.modelLineEdit_8.setObjectName("modelLineEdit_8")
        self.titleLabel_8 = QtWidgets.QLabel(self.tab_8)
        self.titleLabel_8.setGeometry(QtCore.QRect(60, 20, 661, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.titleLabel_8.setFont(font)
        self.titleLabel_8.setTextFormat(QtCore.Qt.AutoText)
        self.titleLabel_8.setScaledContents(False)
        self.titleLabel_8.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel_8.setWordWrap(False)
        self.titleLabel_8.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.titleLabel_8.setObjectName("titleLabel_8")
        self.logLabel_8 = QtWidgets.QLabel(self.tab_8)
        self.logLabel_8.setGeometry(QtCore.QRect(40, 460, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.logLabel_8.setFont(font)
        self.logLabel_8.setTextFormat(QtCore.Qt.AutoText)
        self.logLabel_8.setScaledContents(False)
        self.logLabel_8.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.logLabel_8.setWordWrap(False)
        self.logLabel_8.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.logLabel_8.setObjectName("logLabel_8")
        self.fieldLabel_8 = QtWidgets.QLabel(self.tab_8)
        self.fieldLabel_8.setGeometry(QtCore.QRect(40, 320, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.fieldLabel_8.setFont(font)
        self.fieldLabel_8.setTextFormat(QtCore.Qt.AutoText)
        self.fieldLabel_8.setScaledContents(False)
        self.fieldLabel_8.setWordWrap(False)
        self.fieldLabel_8.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.fieldLabel_8.setObjectName("fieldLabel_8")
        self.fieldlineEdit_8 = QtWidgets.QLineEdit(self.tab_8)
        self.fieldlineEdit_8.setGeometry(QtCore.QRect(40, 350, 281, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fieldlineEdit_8.setFont(font)
        self.fieldlineEdit_8.setObjectName("fieldlineEdit_8")
        self.modelBtn_8 = QtWidgets.QPushButton(self.tab_8)
        self.modelBtn_8.setGeometry(QtCore.QRect(350, 190, 61, 31))
        self.modelBtn_8.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.modelBtn_8.setObjectName("modelBtn_8")
        self.modelInfoBtn_8 = QtWidgets.QPushButton(self.tab_8)
        self.modelInfoBtn_8.setGeometry(QtCore.QRect(560, 260, 171, 31))
        self.modelInfoBtn_8.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.modelInfoBtn_8.setObjectName("modelInfoBtn_8")
        self.fieldBtn_8 = QtWidgets.QPushButton(self.tab_8)
        self.fieldBtn_8.setGeometry(QtCore.QRect(350, 350, 61, 31))
        self.fieldBtn_8.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.fieldBtn_8.setObjectName("fieldBtn_8")
        self.xlsSaveLineEdit_8 = QtWidgets.QLineEdit(self.tab_8)
        self.xlsSaveLineEdit_8.setGeometry(QtCore.QRect(450, 190, 281, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.xlsSaveLineEdit_8.setFont(font)
        self.xlsSaveLineEdit_8.setObjectName("xlsSaveLineEdit_8")
        self.xlsSaveBtn_8 = QtWidgets.QPushButton(self.tab_8)
        self.xlsSaveBtn_8.setGeometry(QtCore.QRect(770, 190, 51, 31))
        self.xlsSaveBtn_8.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.xlsSaveBtn_8.setObjectName("xlsSaveBtn_8")
        self.xlsSavelLabel_8 = QtWidgets.QLabel(self.tab_8)
        self.xlsSavelLabel_8.setGeometry(QtCore.QRect(450, 160, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.xlsSavelLabel_8.setFont(font)
        self.xlsSavelLabel_8.setTextFormat(QtCore.Qt.AutoText)
        self.xlsSavelLabel_8.setScaledContents(False)
        self.xlsSavelLabel_8.setWordWrap(False)
        self.xlsSavelLabel_8.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.xlsSavelLabel_8.setObjectName("xlsSavelLabel_8")
        self.outdoorcheckBox_8 = QtWidgets.QCheckBox(self.tab_8)
        self.outdoorcheckBox_8.setGeometry(QtCore.QRect(40, 260, 271, 31))
        self.outdoorcheckBox_8.setObjectName("outdoorcheckBox_8")
        self.tabWidget.addTab(self.tab_8, "")
        # </editor-fold>

        # <editor-fold desc="Button Connection">
        # Tool 1
        self.cb1Button.clicked.connect(self.cb1_open)
        self.bmButton.clicked.connect(self.pic_open)
        self.umFolder.clicked.connect(self.folder_open)
        self.exeRun.clicked.connect(self.exe_run)

        # Tool 2
        self.cb1Button_2.clicked.connect(self.cb1_open_method2)
        self.bLibButton.clicked.connect(self.blib_button)
        self.uLibButton.clicked.connect(self.ulib_button)
        self.aStatisticButton.clicked.connect(self.attribute_statistic_button)
        self.mrFolderButton.clicked.connect(self.result_folder_button)
        self.attrAddButton.clicked.connect(self.attribute_add_button)

        # Tool 3
        self.cb1File_3.clicked.connect(self.cb1_open_btn3)
        self.cb1SaveButton.clicked.connect(self.cb1_save_btn3)
        self.floorMergeButton.clicked.connect(self.floor_merge_btn)

        # Tool 4
        self.cb1File_4.clicked.connect(self.cb1_open_btn4)
        self.rFolderBtn_4.clicked.connect(self.folder_open_btn4)
        self.jsIdRecodingBtn_4.clicked.connect(self.id_recoding_btn4)

        # Tool 5
        self.cb1File_5.clicked.connect(self.cb1_open_btn5)
        self.cusCb1Btn_5.clicked.connect(self.cus_cb1_open_btn5)
        self.uLibBtn_5.clicked.connect(self.ulib_btn5)
        self.rFolderBtn_5.clicked.connect(self.folder_open_btn5)
        self.cusModelRunBtn_5.clicked.connect(self.custom_model_replace_btn5)

        # Tool 6
        self.cb1File_6.clicked.connect(self.cb1_open_btn6)
        self.rFolderBtn_6.clicked.connect(self.folder_open_btn6)
        self.versionRunBtn_6.clicked.connect(self.version_run_btn6)

        # Tool 7
        self.modelBtn_7.clicked.connect(self.jump_dialog_btn7)
        self.cb1File_7.clicked.connect(self.cb1_open_btn7)
        self.rFolderBtn_7.clicked.connect(self.folder_open_btn7)
        self.modelShapeBtn_7.clicked.connect(self.model_shape_btn7)

        # Tool 8
        self.cb1File_8.clicked.connect(self.cb1_open_btn8)
        self.modelBtn_8.clicked.connect(self.jump_dialog_btn8)
        self.xlsSaveBtn_8.clicked.connect(self.xls_save_btn8)
        self.modelInfoBtn_8.clicked.connect(self.model_info_extract_btn8)
        self.fieldBtn_8.clicked.connect(self.jump_dialog_btn8)
        self.rFolderBtn_8.clicked.connect(self.folder_open_btn8)
        self.AttrRunBtn_8.clicked.connect(self.model_attributes_add_btn8)
        # </editor-fold>

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # 状态栏动态显示时间
        timer = QtCore.QTimer(self)
        timer.timeout.connect(self.status_showtime)
        timer.start()

        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CB1 Operation ToolBoxes"))
        self.cb1Button.setText(_translate("MainWindow", "open"))
        self.cb1Label.setText(_translate("MainWindow", "Cb1 File"))
        self.bmButton.setText(_translate("MainWindow", "open"))
        self.bmLabel.setText(_translate("MainWindow", "Basemap"))
        self.floorLabel.setText(_translate("MainWindow", "Floor"))
        self.umLabel.setText(_translate("MainWindow", "Campus Builder Basemap Path"))
        self.umFolder.setText(_translate("MainWindow", "open"))
        self.logLabel.setText(_translate("MainWindow", " Log"))
        self.exeRun.setText(_translate("MainWindow", "Run"))
        self.titleLabel.setText(_translate("MainWindow", "Cb1 Basemap Add Tool"))
        self.checkBox.setText(_translate("MainWindow", "Delete (Indoor Features)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tool 1"))

        self.titleLabel_2.setText(_translate("MainWindow", "Basic Attributes Statistic & Add Tool"))
        self.cb1Label_2.setText(_translate("MainWindow", "Cb1 Files"))
        self.cb1Button_2.setText(_translate("MainWindow", "open"))
        self.bLibLabel.setText(_translate("MainWindow", "BundleLib"))
        self.bLibButton.setText(_translate("MainWindow", "open"))
        self.uLibLabel.setText(_translate("MainWindow", "UserLib"))
        self.uLibButton.setText(_translate("MainWindow", "open"))
        self.aStatisticButton.setText(_translate("MainWindow", "Attributes Statistics"))
        self.fieldLabel.setText(_translate("MainWindow", "Field  Add"))
        self.mrFolderLabel.setText(_translate("MainWindow", "Model Results Folder"))
        self.mrFolderButton.setText(_translate("MainWindow", "open"))
        self.logLabel_2.setText(_translate("MainWindow", " Log"))
        self.outdoorCheckBox02.setText(_translate("MainWindow", "Outdoor Scene"))
        self.attrAddButton.setText(_translate("MainWindow", "Attributes Add"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tool 2"))

        self.titleLabel_3.setText(_translate("MainWindow", " Cb1 Floor Scene Merge"))
        self.cb1Label_3.setText(_translate("MainWindow", "Cb1 Files"))
        self.cb1File_3.setText(_translate("MainWindow", "open"))
        self.cb1SaveLabel.setText(_translate("MainWindow", "Cb1 Result Path "))
        self.cb1SaveButton.setText(_translate("MainWindow", "Save"))
        self.bNameCodeLabel.setText(_translate("MainWindow", "Building Name Code(Optional)"))
        self.floorMergeButton.setText(_translate("MainWindow", "Floor Merge"))
        self.logLabel_3.setText(_translate("MainWindow", " Log"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Tool 3"))

        self.rFolderLabel_4.setText(_translate("MainWindow", "Result Folder "))
        self.cb1Label_4.setText(_translate("MainWindow", "Cb1 Files"))
        self.cb1File_4.setText(_translate("MainWindow", "open"))
        self.titleLabel_4.setText(_translate("MainWindow", " Cb1 Id Recoding"))
        self.logLabel_4.setText(_translate("MainWindow", " Log"))
        self.jsIdRecodingBtn_4.setText(_translate("MainWindow", "Json Id Recoding"))
        self.rFolderBtn_4.setText(_translate("MainWindow", "open"))
        self.bNameCodeLabel_2.setText(_translate("MainWindow", "Building Name Code"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Tool 4"))

        self.cb1File_5.setText(_translate("MainWindow", "open"))
        self.titleLabel_5.setText(_translate("MainWindow", "Custom Model Replacement"))
        self.logLabel_5.setText(_translate("MainWindow", " Log"))
        self.modelMmdLabel.setText(_translate("MainWindow", "Model Id (which need be Replaced)"))
        self.cusCb1Label_5.setText(_translate("MainWindow", "Custom Model scene （cb1 - indoor）"))
        self.cusModelRunBtn_5.setText(_translate("MainWindow", "Run"))
        self.cusCb1Btn_5.setText(_translate("MainWindow", "open"))
        self.cb1Label_5.setText(_translate("MainWindow", "Cb1 Files"))
        self.cusModelLabel.setText(_translate("MainWindow", "Custom Model Id (target model)"))
        self.rFolderLabel_5.setText(_translate("MainWindow", "Result Folder"))
        self.rFolderBtn_5.setText(_translate("MainWindow", "open"))
        self.uLibLabel_5.setText(_translate("MainWindow", "UserLib (Custom Model Database)"))
        self.uLibBtn_5.setText(_translate("MainWindow", "open"))
        self.outdoorCheckBox05.setText(_translate("MainWindow", "Outdoor Scene"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Tool 5"))

        self.cb1File_6.setText(_translate("MainWindow", "open"))
        self.titleLabel_6.setText(_translate("MainWindow", "Cb1 version (Rename)"))
        self.logLabel_6.setText(_translate("MainWindow", " Log"))
        self.rFolderLabel_6.setText(_translate("MainWindow", "Result Folder "))
        self.versionRunBtn_6.setText(_translate("MainWindow", "Run"))
        self.rFolderBtn_6.setText(_translate("MainWindow", "open"))
        self.cb1Label_6.setText(_translate("MainWindow", "Cb1 Files"))
        self.bNameLabel_6.setText(_translate("MainWindow", "Building Name (abbreviation)"))
        self.versionLabel_6.setText(_translate("MainWindow", "Version (cb1)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Tool 6"))

        self.modelShapeBtn_7.setText(_translate("MainWindow", "Run"))
        self.cb1Label_7.setText(_translate("MainWindow", "Cb1 Files"))
        self.cb1File_7.setText(_translate("MainWindow", "open"))
        self.rFolderBtn_7.setText(_translate("MainWindow", "open"))
        self.modelLabel_7.setText(_translate("MainWindow", "Model Id (which need be modidy)"))
        self.rFolderLabel_7.setText(_translate("MainWindow", "Result Folder"))
        self.titleLabel_7.setText(_translate("MainWindow", "Model Shape Height & Space Height Modify"))
        self.logLabel_7.setText(_translate("MainWindow", " Log"))
        self.hPoseLabel_7.setText(_translate("MainWindow", "Pose Height Modify(Optional)"))
        self.hScaleLabel_7.setText(_translate("MainWindow", "Scale Height Modify(Optional)"))
        self.modelBtn_7.setText(_translate("MainWindow", "open"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Tool 7"))

        self.AttrRunBtn_8.setText(_translate("MainWindow", "Run"))
        self.cb1Label_8.setText(_translate("MainWindow", "Cb1 Files"))
        self.cb1File_8.setText(_translate("MainWindow", "open"))
        self.rFolderBtn_8.setText(_translate("MainWindow", "open"))
        self.modelLabel_8.setText(_translate("MainWindow", "Model Id"))
        self.rFolderLabel_8.setText(_translate("MainWindow", "Result Folder"))
        self.titleLabel_8.setText(_translate("MainWindow", "Model Advanced Attributes Add "))
        self.logLabel_8.setText(_translate("MainWindow", " Log"))
        self.fieldLabel_8.setText(_translate("MainWindow", "Fields (which need be added)"))
        self.modelBtn_8.setText(_translate("MainWindow", "open"))
        self.modelInfoBtn_8.setText(_translate("MainWindow", "Model Info Extract"))
        self.fieldBtn_8.setText(_translate("MainWindow", "open"))
        self.xlsSaveBtn_8.setText(_translate("MainWindow", "Save"))
        self.xlsSavelLabel_8.setText(_translate("MainWindow", "Model Xls Path"))
        self.outdoorcheckBox_8.setText(_translate("MainWindow", "Outdoor Scene"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "Tool 8"))

        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))

    def status_showtime(self):
        self.statusbar.showMessage('Time : {}'.format(QtCore.QDateTime.currentDateTime().toString()))

# if __name__ == '__main__':
#     import sys
#
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
